<?php
// +----------------------------------------------------------------------
// | ThinkBiz System
// | 功能： 门户模块内容控制器 
// +----------------------------------------------------------------------
// | 版权所有 2013~2017 深圳市俊网网络有限公司 [ http://www.junnet.net ]
// +----------------------------------------------------------------------
// | 官方网站：http://www.junnet.net
// +----------------------------------------------------------------------
// | 作者: 余剑华 <528526198@qq.com>
// +----------------------------------------------------------------------

/**
 * 菜单信息
 */
return [
  [
    'module' => 'web',
    'name' => '',
    'attach' => '',
    'title' => '{"zh-cn":"内容管理","en-us":"Content Management"}',
    'level' => 1,
    'type' => 1,
    'status' => 1,
    'icon' => 'fa fa-fw fa-th-list',
    'sort' => 50,
    'contet_sign' => 'web',
    'child' => [
      [
        'module' => 'web',
        'name' => 'web/content/index',
        'attach' => 'model=goods',
        'title' => '{"zh-cn":"标准商品"}',
        'level' => 2,
        'type' => 1,
        'status' => 0,
        'icon' => 'fa fa-fw fa-list',
        'sort' => 50,
        'contet_sign' => '',
        'child' => [
          [
            'module' => 'web',
            'name' => 'web/content/add',
            'attach' => 'model=goods',
            'title' => '{"zh-cn":"新增"}',
            'level' => 3,
            'type' => 1,
            'status' => 0,
            'icon' => '',
            'sort' => 50,
            'contet_sign' => '',
          ],
          [
            'module' => 'web',
            'name' => 'web/content/save',
            'attach' => 'model=goods',
            'title' => '{"zh-cn":"保存数据"}',
            'level' => 3,
            'type' => 1,
            'status' => 0,
            'icon' => '',
            'sort' => 50,
            'contet_sign' => '',
          ],
          [
            'module' => 'web',
            'name' => 'web/content/edit',
            'attach' => 'model=goods',
            'title' => '{"zh-cn":"编辑"}',
            'level' => 3,
            'type' => 1,
            'status' => 0,
            'icon' => '',
            'sort' => 50,
            'contet_sign' => '',
          ],
          [
            'module' => 'web',
            'name' => 'web/content/update',
            'attach' => 'model=goods',
            'title' => '{"zh-cn":"更新数据"}',
            'level' => 3,
            'type' => 1,
            'status' => 0,
            'icon' => '',
            'sort' => 50,
            'contet_sign' => '',
          ],
          [
            'module' => 'web',
            'name' => 'web/content/dels',
            'attach' => 'model=goods',
            'title' => '{"zh-cn":"批量删除"}',
            'level' => 3,
            'type' => 1,
            'status' => 0,
            'icon' => '',
            'sort' => 50,
            'contet_sign' => '',
          ],
          [
            'module' => 'web',
            'name' => 'web/content/del',
            'attach' => 'model=goods',
            'title' => '{"zh-cn":"删除"}',
            'level' => 3,
            'type' => 1,
            'status' => 0,
            'icon' => '',
            'sort' => 50,
            'contet_sign' => '',
          ],
          [
            'module' => 'web',
            'name' => 'web/content/sort',
            'attach' => 'model=goods',
            'title' => '{"zh-cn":"修改排序"}',
            'level' => 3,
            'type' => 1,
            'status' => 0,
            'icon' => '',
            'sort' => 50,
            'contet_sign' => '',
          ],
          [
            'module' => 'web',
            'name' => 'web/content/switch',
            'attach' => 'model=goods',
            'title' => '{"zh-cn":"切换状态"}',
            'level' => 3,
            'type' => 1,
            'status' => 0,
            'icon' => '',
            'sort' => 50,
            'contet_sign' => '',
          ],
        ],
      ],
      [
        'module' => 'web',
        'name' => 'web/content/index',
        'attach' => 'model=video',
        'title' => '{"zh-cn":"视频模型"}',
        'level' => 2,
        'type' => 1,
        'status' => 0,
        'icon' => 'fa fa-fw fa-list',
        'sort' => 50,
        'contet_sign' => '',
        'child' => [
          [
            'module' => 'web',
            'name' => 'web/content/switch',
            'attach' => 'model=video',
            'title' => '{"zh-cn":"切换状态"}',
            'level' => 3,
            'type' => 1,
            'status' => 0,
            'icon' => '',
            'sort' => 50,
            'contet_sign' => '',
          ],
          [
            'module' => 'web',
            'name' => 'web/content/sort',
            'attach' => 'model=video',
            'title' => '{"zh-cn":"修改排序"}',
            'level' => 3,
            'type' => 1,
            'status' => 0,
            'icon' => '',
            'sort' => 50,
            'contet_sign' => '',
          ],
          [
            'module' => 'web',
            'name' => 'web/content/add',
            'attach' => 'model=video',
            'title' => '{"zh-cn":"新增"}',
            'level' => 3,
            'type' => 1,
            'status' => 0,
            'icon' => '',
            'sort' => 50,
            'contet_sign' => '',
          ],
          [
            'module' => 'web',
            'name' => 'web/content/del',
            'attach' => 'model=video',
            'title' => '{"zh-cn":"删除"}',
            'level' => 3,
            'type' => 1,
            'status' => 0,
            'icon' => '',
            'sort' => 50,
            'contet_sign' => '',
          ],
          [
            'module' => 'web',
            'name' => 'web/content/update',
            'attach' => 'model=video',
            'title' => '{"zh-cn":"更新数据"}',
            'level' => 3,
            'type' => 1,
            'status' => 0,
            'icon' => '',
            'sort' => 50,
            'contet_sign' => '',
          ],
          [
            'module' => 'web',
            'name' => 'web/content/edit',
            'attach' => 'model=video',
            'title' => '{"zh-cn":"编辑"}',
            'level' => 3,
            'type' => 1,
            'status' => 0,
            'icon' => '',
            'sort' => 50,
            'contet_sign' => '',
          ],
          [
            'module' => 'web',
            'name' => 'web/content/save',
            'attach' => 'model=video',
            'title' => '{"zh-cn":"保存数据"}',
            'level' => 3,
            'type' => 1,
            'status' => 0,
            'icon' => '',
            'sort' => 50,
            'contet_sign' => '',
          ],
          [
            'module' => 'web',
            'name' => 'web/content/dels',
            'attach' => 'model=video',
            'title' => '{"zh-cn":"批量删除"}',
            'level' => 3,
            'type' => 1,
            'status' => 0,
            'icon' => '',
            'sort' => 50,
            'contet_sign' => '',
          ],
        ],
      ],
      [
        'module' => 'web',
        'name' => 'web/content/index',
        'attach' => 'model=product',
        'title' => '{"zh-cn":"产品模型"}',
        'level' => 2,
        'type' => 1,
        'status' => 1,
        'icon' => 'fa fa-fw fa-list',
        'sort' => 50,
        'contet_sign' => '',
        'child' => [
          [
            'module' => 'web',
            'name' => 'web/content/switch',
            'attach' => 'model=product',
            'title' => '{"zh-cn":"切换状态"}',
            'level' => 3,
            'type' => 1,
            'status' => 0,
            'icon' => '',
            'sort' => 50,
            'contet_sign' => '',
          ],
          [
            'module' => 'web',
            'name' => 'web/content/sort',
            'attach' => 'model=product',
            'title' => '{"zh-cn":"修改排序"}',
            'level' => 3,
            'type' => 1,
            'status' => 0,
            'icon' => '',
            'sort' => 50,
            'contet_sign' => '',
          ],
          [
            'module' => 'web',
            'name' => 'web/content/edit',
            'attach' => 'model=product',
            'title' => '{"zh-cn":"编辑"}',
            'level' => 3,
            'type' => 1,
            'status' => 0,
            'icon' => '',
            'sort' => 50,
            'contet_sign' => '',
          ],
          [
            'module' => 'web',
            'name' => 'web/content/update',
            'attach' => 'model=product',
            'title' => '{"zh-cn":"更新数据"}',
            'level' => 3,
            'type' => 1,
            'status' => 0,
            'icon' => '',
            'sort' => 50,
            'contet_sign' => '',
          ],
          [
            'module' => 'web',
            'name' => 'web/content/del',
            'attach' => 'model=product',
            'title' => '{"zh-cn":"删除"}',
            'level' => 3,
            'type' => 1,
            'status' => 0,
            'icon' => '',
            'sort' => 50,
            'contet_sign' => '',
          ],
          [
            'module' => 'web',
            'name' => 'web/content/dels',
            'attach' => 'model=product',
            'title' => '{"zh-cn":"批量删除"}',
            'level' => 3,
            'type' => 1,
            'status' => 0,
            'icon' => '',
            'sort' => 50,
            'contet_sign' => '',
          ],
          [
            'module' => 'web',
            'name' => 'web/content/save',
            'attach' => 'model=product',
            'title' => '{"zh-cn":"保存数据"}',
            'level' => 3,
            'type' => 1,
            'status' => 0,
            'icon' => '',
            'sort' => 50,
            'contet_sign' => '',
          ],
          [
            'module' => 'web',
            'name' => 'web/content/add',
            'attach' => 'model=product',
            'title' => '{"zh-cn":"新增"}',
            'level' => 3,
            'type' => 1,
            'status' => 0,
            'icon' => '',
            'sort' => 50,
            'contet_sign' => '',
          ],
        ],
      ],
      [
        'module' => 'web',
        'name' => 'web/content/index',
        'attach' => 'model=article',
        'title' => '{"zh-cn":"普通文章"}',
        'level' => 2,
        'type' => 1,
        'status' => 1,
        'icon' => 'fa fa-fw fa-list',
        'sort' => 50,
        'contet_sign' => '',
        'child' => [
          [
            'module' => 'web',
            'name' => 'web/content/sort',
            'attach' => 'model=article',
            'title' => '{"zh-cn":"修改排序"}',
            'level' => 3,
            'type' => 1,
            'status' => 0,
            'icon' => '',
            'sort' => 50,
            'contet_sign' => '',
          ],
          [
            'module' => 'web',
            'name' => 'web/content/switch',
            'attach' => 'model=article',
            'title' => '{"zh-cn":"切换状态"}',
            'level' => 3,
            'type' => 1,
            'status' => 0,
            'icon' => '',
            'sort' => 50,
            'contet_sign' => '',
          ],
          [
            'module' => 'web',
            'name' => 'web/content/dels',
            'attach' => 'model=article',
            'title' => '{"zh-cn":"批量删除"}',
            'level' => 3,
            'type' => 1,
            'status' => 0,
            'icon' => '',
            'sort' => 50,
            'contet_sign' => '',
          ],
          [
            'module' => 'web',
            'name' => 'web/content/edit',
            'attach' => 'model=article',
            'title' => '{"zh-cn":"编辑"}',
            'level' => 3,
            'type' => 1,
            'status' => 0,
            'icon' => '',
            'sort' => 50,
            'contet_sign' => '',
          ],
          [
            'module' => 'web',
            'name' => 'web/content/update',
            'attach' => 'model=article',
            'title' => '{"zh-cn":"更新数据"}',
            'level' => 3,
            'type' => 1,
            'status' => 0,
            'icon' => '',
            'sort' => 50,
            'contet_sign' => '',
          ],
          [
            'module' => 'web',
            'name' => 'web/content/del',
            'attach' => 'model=article',
            'title' => '{"zh-cn":"删除"}',
            'level' => 3,
            'type' => 1,
            'status' => 0,
            'icon' => '',
            'sort' => 50,
            'contet_sign' => '',
          ],
          [
            'module' => 'web',
            'name' => 'web/content/save',
            'attach' => 'model=article',
            'title' => '{"zh-cn":"保存数据"}',
            'level' => 3,
            'type' => 1,
            'status' => 0,
            'icon' => '',
            'sort' => 50,
            'contet_sign' => '',
          ],
          [
            'module' => 'web',
            'name' => 'web/content/add',
            'attach' => 'model=article',
            'title' => '{"zh-cn":"新增"}',
            'level' => 3,
            'type' => 1,
            'status' => 0,
            'icon' => '',
            'sort' => 50,
            'contet_sign' => '',
          ],
        ],
      ],
    ],
  ],
  [
    'module' => 'web',
    'name' => '',
    'attach' => '',
    'title' => '{"zh-cn":"\\u95e8\\u6237\\u8bbe\\u7f6e","en-us":"web Config"}',
    'level' => 1,
    'type' => 1,
    'status' => 1,
    'icon' => 'fa fa-fw fa-cogs',
    'sort' => 50,
    'contet_sign' => '',
    'child' => [
      [
        'module' => 'web',
        'name' => 'web/Category/index',
        'attach' => '',
        'title' => '{"zh-cn":"\\u5185\\u5bb9\\u680f\\u76ee","en-us":"Category"}',
        'level' => 2,
        'type' => 1,
        'status' => 1,
        'icon' => 'glyphicon glyphicon-th-list',
        'sort' => 50,
        'contet_sign' => '',
        'child' => [
          [
            'module' => 'web',
            'name' => 'web/Category/switch',
            'attach' => '',
            'title' => '{"zh-cn":"\\u5207\\u6362\\u680f\\u76ee\\u72b6\\u6001","en-us":"Change the cate status"}',
            'level' => 3,
            'type' => 1,
            'status' => 2,
            'icon' => '',
            'sort' => 50,
            'contet_sign' => '',
          ],
          [
            'module' => 'web',
            'name' => 'web/Category/dels',
            'attach' => '',
            'title' => '{"zh-cn":"\\u6279\\u91cf\\u5220\\u9664\\u680f\\u76ee","en-us":"Batch delete"}',
            'level' => 3,
            'type' => 1,
            'status' => 2,
            'icon' => '',
            'sort' => 50,
            'contet_sign' => '',
          ],
          [
            'module' => 'web',
            'name' => 'web/Category/sort',
            'attach' => '',
            'title' => '{"zh-cn":"\\u680f\\u76ee\\u6392\\u5e8f","en-us":"Sort the Cate"}',
            'level' => 3,
            'type' => 1,
            'status' => 2,
            'icon' => '',
            'sort' => 50,
            'contet_sign' => '',
          ],
          [
            'module' => 'web',
            'name' => 'web/Category/del',
            'attach' => '',
            'title' => '{"zh-cn":"\\u5220\\u9664\\u680f\\u76ee","en-us":"Delete the Cate"}',
            'level' => 3,
            'type' => 1,
            'status' => 2,
            'icon' => '',
            'sort' => 50,
            'contet_sign' => '',
          ],
          [
            'module' => 'web',
            'name' => 'web/Category/update',
            'attach' => '',
            'title' => '{"zh-cn":"\\u66f4\\u65b0\\u680f\\u76ee\\u6570\\u636e","en-us":"Update the Cate"}',
            'level' => 3,
            'type' => 1,
            'status' => 2,
            'icon' => '',
            'sort' => 50,
            'contet_sign' => '',
          ],
          [
            'module' => 'web',
            'name' => 'web/Category/add',
            'attach' => '',
            'title' => '{"zh-cn":"\\u65b0\\u589e\\u680f\\u76ee","en-us":"Add Cate"}',
            'level' => 3,
            'type' => 1,
            'status' => 2,
            'icon' => '',
            'sort' => 50,
            'contet_sign' => '',
          ],
          [
            'module' => 'web',
            'name' => 'web/Category/edit',
            'attach' => '',
            'title' => '{"zh-cn":"\\u7f16\\u8f91\\u680f\\u76ee","en-us":"Edit the Cate"}',
            'level' => 3,
            'type' => 1,
            'status' => 2,
            'icon' => '',
            'sort' => 50,
            'contet_sign' => '',
          ],
          [
            'module' => 'web',
            'name' => 'web/Category/save',
            'attach' => '',
            'title' => '{"zh-cn":"\\u4fdd\\u5b58\\u680f\\u76ee\\u6570\\u636e","en-us":"Save the Cate"}',
            'level' => 3,
            'type' => 1,
            'status' => 2,
            'icon' => '',
            'sort' => 50,
            'contet_sign' => '',
          ],
        ],
      ],
      [
        'module' => 'web',
        'name' => 'web/Model/index',
        'attach' => '',
        'title' => '{"zh-cn":"\\u6a21\\u578b\\u7ba1\\u7406","en-us":"Model Management"}',
        'level' => 2,
        'type' => 1,
        'status' => 1,
        'icon' => 'fa fa-fw fa-dashboard',
        'sort' => 50,
        'contet_sign' => '',
        'child' => [
          [
            'module' => 'web',
            'name' => 'web/Model/sys_field',
            'attach' => '',
            'title' => '{"zh-cn":"\\u7cfb\\u7edf\\u5b57\\u6bb5\\u7ba1\\u7406","en-us":"Manage the system fields"}',
            'level' => 3,
            'type' => 1,
            'status' => 2,
            'icon' => '',
            'sort' => 50,
            'contet_sign' => '',
          ],
          [
            'module' => 'web',
            'name' => 'web/Model/field_sort',
            'attach' => '',
            'title' => '{"zh-cn":"\\u4fee\\u6539\\u5b57\\u6bb5\\u6392\\u5e8f","en-us":"Change the field sort"}',
            'level' => 3,
            'type' => 1,
            'status' => 2,
            'icon' => '',
            'sort' => 50,
            'contet_sign' => '',
          ],
          [
            'module' => 'web',
            'name' => 'web/Model/field_show',
            'attach' => '',
            'title' => '{"zh-cn":"\\u5207\\u6362\\u5b57\\u6bb5\\u7684\\u8868\\u5355\\u663e\\u9690\\u72b6\\u6001","en-us":"Change the field show"}',
            'level' => 3,
            'type' => 1,
            'status' => 2,
            'icon' => '',
            'sort' => 50,
            'contet_sign' => '',
          ],
          [
            'module' => 'web',
            'name' => 'web/Model/field_switch',
            'attach' => '',
            'title' => '{"zh-cn":"\\u5207\\u6362\\u5b57\\u6bb5\\u72b6\\u6001","en-us":"Change the field status"}',
            'level' => 3,
            'type' => 1,
            'status' => 2,
            'icon' => '',
            'sort' => 50,
            'contet_sign' => '',
          ],
          [
            'module' => 'web',
            'name' => 'web/Model/field_edit',
            'attach' => '',
            'title' => '{"zh-cn":"\\u7f16\\u8f91\\u5b57\\u6bb5","en-us":"Edit the field"}',
            'level' => 3,
            'type' => 1,
            'status' => 2,
            'icon' => '',
            'sort' => 50,
            'contet_sign' => '',
          ],
          [
            'module' => 'web',
            'name' => 'web/Model/field_update',
            'attach' => '',
            'title' => '{"zh-cn":"\\u66f4\\u65b0\\u5b57\\u6bb5\\u6570\\u636e","en-us":"Save the field data"}',
            'level' => 3,
            'type' => 1,
            'status' => 2,
            'icon' => '',
            'sort' => 50,
            'contet_sign' => '',
          ],
          [
            'module' => 'web',
            'name' => 'web/Model/field_del',
            'attach' => '',
            'title' => '{"zh-cn":"\\u5220\\u9664\\u5b57\\u6bb5","en-us":"Delete the field"}',
            'level' => 3,
            'type' => 1,
            'status' => 2,
            'icon' => '',
            'sort' => 50,
            'contet_sign' => '',
          ],
          [
            'module' => 'web',
            'name' => 'web/Model/field_save',
            'attach' => '',
            'title' => '{"zh-cn":"\\u4fdd\\u5b58\\u5b57\\u6bb5\\u6570\\u636e","en-us":"Save the field"}',
            'level' => 3,
            'type' => 1,
            'status' => 2,
            'icon' => '',
            'sort' => 50,
            'contet_sign' => '',
          ],
          [
            'module' => 'web',
            'name' => 'web/Model/field',
            'attach' => '',
            'title' => '{"zh-cn":"\\u5b57\\u6bb5\\u7ba1\\u7406","en-us":"Fields management"}',
            'level' => 3,
            'type' => 1,
            'status' => 2,
            'icon' => '',
            'sort' => 50,
            'contet_sign' => '',
          ],
          [
            'module' => 'web',
            'name' => 'web/Model/field_add',
            'attach' => '',
            'title' => '{"zh-cn":"\\u65b0\\u589e\\u5b57\\u6bb5","en-us":"Add field"}',
            'level' => 3,
            'type' => 1,
            'status' => 2,
            'icon' => '',
            'sort' => 50,
            'contet_sign' => '',
          ],
          [
            'module' => 'web',
            'name' => 'web/Model/switch',
            'attach' => '',
            'title' => '{"zh-cn":"\\u5207\\u6362\\u6a21\\u578b\\u72b6\\u6001","en-us":"Change the model status"}',
            'level' => 3,
            'type' => 1,
            'status' => 2,
            'icon' => '',
            'sort' => 50,
            'contet_sign' => '',
          ],
          [
            'module' => 'web',
            'name' => 'web/Model/dels',
            'attach' => '',
            'title' => '{"zh-cn":"\\u6279\\u91cf\\u5220\\u9664\\u6a21\\u578b","en-us":"Batch delete the model"}',
            'level' => 3,
            'type' => 1,
            'status' => 2,
            'icon' => '',
            'sort' => 50,
            'contet_sign' => '',
          ],
          [
            'module' => 'web',
            'name' => 'web/Model/del',
            'attach' => '',
            'title' => '{"zh-cn":"\\u5220\\u9664\\u6a21\\u578b","en-us":"Delete the model"}',
            'level' => 3,
            'type' => 1,
            'status' => 2,
            'icon' => '',
            'sort' => 50,
            'contet_sign' => '',
          ],
          [
            'module' => 'web',
            'name' => 'web/Model/edit',
            'attach' => '',
            'title' => '{"zh-cn":"\\u7f16\\u8f91\\u6a21\\u578b","en-us":"Edit the model"}',
            'level' => 3,
            'type' => 1,
            'status' => 2,
            'icon' => '',
            'sort' => 50,
            'contet_sign' => '',
          ],
          [
            'module' => 'web',
            'name' => 'web/Model/update',
            'attach' => '',
            'title' => '{"zh-cn":"\\u66f4\\u65b0\\u6a21\\u578b\\u6570\\u636e","en-us":"Update the model"}',
            'level' => 3,
            'type' => 1,
            'status' => 2,
            'icon' => '',
            'sort' => 50,
            'contet_sign' => '',
          ],
          [
            'module' => 'web',
            'name' => 'web/Model/save',
            'attach' => '',
            'title' => '{"zh-cn":"\\u4fdd\\u5b58\\u6a21\\u578b\\u6570\\u636e","en-us":"Save the Model"}',
            'level' => 3,
            'type' => 1,
            'status' => 2,
            'icon' => '',
            'sort' => 50,
            'contet_sign' => '',
          ],
          [
            'module' => 'web',
            'name' => 'web/Model/add',
            'attach' => '',
            'title' => '{"zh-cn":"\\u65b0\\u589e\\u6a21\\u578b","en-us":"Add Model"}',
            'level' => 3,
            'type' => 1,
            'status' => 0,
            'icon' => '',
            'sort' => 50,
            'contet_sign' => '',
          ],
        ],
      ],
    ],
  ],
];
