<?php
/**
 * Created by PhpStorm.
 * User: iconblog
 * Date: 2017/10/18
 * Time: 上午9:38
 */

namespace app\sys\controller;

use app\common\JunCreater\JCreater;
use app\sys\model\FriendlyLink as FriendLinkModel;

class FriendlyLink extends AdminBase
{

    /**
     * @var mixed
     */
    protected $fl;


    /**
     *
     */
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->fl = new FriendLinkModel();
    }

    /**
     * 友情链接
     * @return mixed
     */
    public function index()
    {

        $FL = $this->fl->adminList();  //取出当前语言版本下的所有配置项
        $friendLinkList = $FL ->all();
        foreach ($friendLinkList as $key=>$fl) {
            $friendLinkList[$key]['url'] = '<a href="'.$fl['url'].'" target="_blank">'.$fl['url'].'</a>';
        }

        $page = $FL->render();
        $this->assign('data',$friendLinkList);
        $this->assign('page', $page);

        return $this->fetch();
    }



    /**
     * 添加友情链接
     * @return mixed
     */
    public function add()
    {

        return $this->fetch();
    }



    /**
     * 编辑
     * @return mixed
     */
    public function edit($id)
    {

        $position = FriendLinkModel::get($id);
        $this->assign('data',$position);
        return $this->fetch();
    }



    /**
     * 保存推荐位
     * @return mixed
     */
    public function save()
    {
        $data = request()->post();
        if( empty($data['name']) ){
            $this->error('请输入推荐位的名称');
        }
        $position = new FriendLinkModel();
        $save = $position->saveLinks($data);
        if( $save['code'] == 0 ){
            $this->error($save['error']);
        }
        $this->success('保存成功!');
    }



    /**
     * 删除推荐位
     * @return mixed
     */
    public function delete()
    {
        if ( empty(request()->post('id')) ){
            $this->error('请选择要删除的推荐位');
        }
        $id = request()->post('id');
        $position = new FriendLinkModel();
        $data = FriendLinkModel::get($id);
        if( empty($data) ){
            $this->error('当前推荐位不存在!');
        }

        $del = $position->deleteLinks($id);
        if( $del['code'] == 0 ){
            $this->error($del['error']);
        }
        $this->success('删除成功!');
    }


    /**
     * 批量删除推荐位
     * @return mixed
     */
    public function deletes()
    {
        if ( empty(request()->post('id')) ){
            $this->error('请选择要删除的推荐位');
        }
        $id = request()->post('id');
        $position = FriendLinkModel::get($id);
        if( empty($position) ){
            $this->error('当前推荐位不存在!');
        }

        $del = $position->deletesLinks($id);
        if( $del['code'] == 0 ){
            $this->error($del['error']);
        }
        $this->success('删除成功!');
    }






    /**
     * 设置友情链接字段
     * @param $id
     */
    public function setVal($id)
    {
        $data = input('');
        if (isset($data['field']) && isset($data['val'])) {
            $field = $data['field'];
            $value = $data['val'];
        } else {
            $field = $data['field_name'];
            $value = $data['field'];
        }

        $res =  $this->fl->save([$field=>$value],['id'=>$id]);
        if ($res!==false) {
            sys_log(lang('comm_update_success'),1);  //操作结果写入系统日志
            $this->success(lang('comm_update_success'));
        } else {
            sys_log(lang('comm_update_error'),0);  //操作结果写入系统日志
            $this->error(lang('comm_update_error'));
        }
    }

}