<?php
/**
 * Created by PhpStorm.
 * User: iconblog
 * Date: 2017/8/9
 * Time: 下午2:43
 */

namespace app\sys\controller;


use app\sys\api\Resource;
use think\Request;

class PictureLibrary extends AdminBase
{
    protected $resource;

    public function __construct(Request $request)
    {
        parent::__construct($request);
        $this->resource = new Resource();
    }

    /**
     * 析构函数
     */
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        /**
         * 后台系统图片库路径
         */
        Resource::$user = 'admin';
    }



    /**
     * 图片库首页
     * @return mixed
     */
    public function index()
    {
        $redata = $this->resource->files('',true);

        if( $redata['code'] == 0 ){
            $this->error($redata['error']);
        }
        $this->assign('list',json_decode($redata['data'],1));;
        $this->assign('path',$this->resource->getNowActualPath());
        $this->assign('show_path',$this->resource->getNowPath());
        return $this->fetch();
    }


    /**
     * 新增目录
     * @return mixed
     */
    public function newFolder()
    {
        $data = request()->param();
        $newFolder = $this->resource->newFolder();

        return $newFolder;
    }



    /**
     * 上传图片
     * @return mixed
     */
    public function upload()
    {
        // 获取文件夹
        $folderList = $this->resource->folderList();

        $this->assign('folderList',json_encode($folderList));
        return $this->fetch();
    }


    /**
     * 图片执行上传
     * @return mixed
     */
    public function doUpload()
    {
        // 上传到当前目录
        $data = $this->resource->fileUpload(request()->param('folder_id'));
        if( $data['code'] == 1 ){
            $this->success('上传成功');
        }else{
            $this->error($data['error']);
        }
    }



    /**
     * 通过ajax加载图片库列表
     * @return array
     */
    public function ajaxList()
    {
        // ajax加载图片库列表
        $data = request()->post();
        if( empty($data['dir']) )
        {
            $this->error('请选择您需要进入的目录!');
        }
        // 获取目录列表
        $list = $this->resource->files($data['dir'],false);
        if( $list['code'] == 0 ){
            $this->error($list['error']);
        }
        $this->assign('list',json_decode($list['data'],1));
        $this->assign('path',$this->resource->getNowActualPath());
        $html = $this->fetch();
        return ['code'=>1,'data'=>$html,'path'=>$this->resource->getNowActualPath(),'show_path' => $this->resource->getNowPath()];
    }





    /**
     * 删除图片库
     * @return mixed
     */
    public function delete()
    {


    }

}