<?php
// +----------------------------------------------------------------------
// | ThinkBiz System
// | 功能： 团购促销后台管理模块
// +----------------------------------------------------------------------
// | 版权所有 2013~2017 深圳市俊网网络有限公司 [ http://www.junnet.net ]
// +----------------------------------------------------------------------
// | 官方网站：http://www.junnet.net
// +----------------------------------------------------------------------
// | 作者: 吴跃忠 <357397264@qq.com>
// +----------------------------------------------------------------------


namespace app\shop\admin;

use app\shop\model\ShopPromotionGroup;
use app\sys\controller\AdminBase;
use app\common\JunCreater\JCreater;
use app\shop\validate\GroupBuying as GroupBuyValidate;
use think\Db;

class GroupBuying extends AdminBase
{
    protected $_DB;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->_DB = new ShopPromotionGroup();
    }

    /**
     * 后台团购管理列表页
     * 后台显示数据：
     *      团购标题
     *      团购价格
     *      购买量
     *      参团总量
     *      开始时间
     *      结束时间
     *      状    态
     *      操    作
     * @return mixed
     */
    public function index()
    {
        //获取当前数据
        //定义当前db
        $field = 'group_id as id,title,goods,price,group_num,buy_num,virtual_buy_num,start_time,end_time,status';
        $groupList = $this->_DB->field($field)->order('group_id desc')->paginate(tb_config('list_rows',1,$this->lang));
        //配合后台表格
        // 是否显示表格的选择列？
        $table['show_check'] = 1;
        //title定义
        $table_head = [
            ['id','ID','text'],
            ['title',lang('prom_group_table_title'),'text'],
            ['goods',lang('prom_group_table_goods'),'text'],
            ['price',lang('prom_group_table_price'),'text'],
            ['group_num',lang('prom_group_table_group_num'),'text'],
            ['buy_num',lang('prom_group_table_buy_num'),'text'],
            ['virtual_buy_num','虚拟购买数','text'],
            ['start_time',lang('start_time'),'text'],
            ['end_time',lang('end_time'),'text'],
            ['status',lang('status'),'text'],
            ['btn',lang('content_list_title_7'),'btn'],
        ];
        $table['tb_title'] = JCreater::table_header($table_head);
        $btn = [
            [lang('comm_btn_edit'),'frame',lang('comm_edit_frame_title'),'fa fa-fw fa-pencil-square-o','layui-btn-normal','GroupBuying/edit','id'],
            [lang('comm_btn_del'),'confirm',lang('comm_del_confirm_msg'),'fa fa-fw fa-trash-o','layui-btn-danger','GroupBuying/del','id'],
        ];
        $table['btn_lst'] = JCreater::table_btn($btn);
        // 设置列表页顶部按钮组
        $top_btn = [
            [lang('comm_btn_add'),'frame',lang('comm_add_frame_title'),'fa fa-fw fa-plus','layui-btn-normal','GroupBuying/add'],
            [lang('comm_btn_dels'),'confirm_form',lang('comm_dels_confirm_msg'),'fa fa-fw fa-trash-o','layui-btn-danger','GroupBuying/del'],
        ];
        $table['top_btn'] = JCreater::table_btn($top_btn);
        // 获取分页显示
        $page = $groupList->render();
        $this->assign('page', $page);
        $this->assign($table);
        $this->assign('data',$groupList);
        return $this->fetch('sys@Base:table');
    }

    public function add()
    {
        $form['action'] = 'save';      //表单提交的目的路径
        $form['web_title'] = lang('prom_group_add_title');   // 页面标题
        $this->assign($form);
        //查找所有用户等级
        $user_level = Db::name('user_level')->field('id,level_name')->select();
        $this->assign('user_level',$user_level);
        return $this->fetch();
    }

    public function edit()
    {
        //查找所有用户等级
        $user_level = Db::name('user_level') ->where('status',1)->field('id,level_name')->select();
        $this->assign('user_level',$user_level);
        //获取抢购数据
        $groupData = $this->_DB->where('group_id',$this->request->param('id'))->find();
        $groupData['user_group_arr'] = explode(',',$groupData['user_group']);
        //获取商品规格信息
        $prom_id = getPromID(2,$groupData['group_id']);
        $goodsspec = Db::name('shop_promotion_goods')->field('goods_id,goods_spec')->where('prom_id',$prom_id)->find();
        //定义商品信息及商品规格信息
        $groupData['goodsspec'] = json_encode(unserialize($goodsspec['goods_spec']),true);
        //商品详细信息
        $goods = Db::name('shop_goods')->where('id',$goodsspec['goods_id'])->field('id,title,shop_price,stock')->find();
        $this->assign('goods',$goods);
        //================  表单项定义 =================
        $form['action'] = 'save';      //表单提交的目的路径
        $form['web_title'] = lang('prom_group_edit_title').'：&nbsp;&nbsp;'.$groupData['title'];   // 页面标题
        $this->assign($form);
        //================  表单项定义 end =================
        $this->assign('groupData',$groupData);
        return $this->fetch();
    }

    public function save()
    {
        $postData  = $this->post_data;
        //数据筛选
        $validate = new GroupBuyValidate();
        $vaData = $validate->check($postData);
        if( !$vaData ) {
            $this->error($validate->getError());
        }
        //数据验证通过，验证商品是否存在
        $field = 'id,shop_price,stock,status';
        $goods = Db::name('shop_goods')->where('id',$postData['goods'])->field($field)->find();
        if( !$goods ) {
            //商品不存在
            $this->error(lang('Goods_not_is_exist'));
        }else{
            //商品是否上架
            if( $goods['shop_price'] < $postData['price'] ){//抢购价格是否大于售卖价格
                $this->error(lang('price_above_shop_price'));
            }
            //全部通过，保存进促销表和抢购表
            unset($postData['file']);
            //确认是编辑还是增加
            //获取规格json字符串,将json字符串转化为序列化数据
            $spec_json = htmlspecialchars_decode($postData['goodsspec']);
            $spec_serialize = '';
            if( !empty($spec_json) ){
                $spec_arr = json_decode($spec_json,true);
                $spec_serialize = serialize($spec_arr);
            }
            if( !empty($postData['group_id']) )
            {
                $group_id = $postData['group_id'];
                $prom_id = Db::name('shop_promotion')->where(['p_type'=>2,'p_id'=>$group_id])->value('prom_id');
                unset($postData['group_id']);
                Db::startTrans();
                try {
                    //保存进抢购表
                    $this->_DB->where('group_id',$group_id)->update($postData);
                    //保存进促销表
                    $promData['goods'] = $postData['goods'];
                    $promData['start_time'] = $postData['start_time'];
                    $promData['end_time'] = $postData['end_time'];
                    Db::name('shop_promotion')->where(['p_type'=>2,'p_id'=>$group_id])->update($promData);
                    $pGoodsData['goods_id'] = $postData['goods'];
                    $pGoodsData['goods_spec'] = $spec_serialize;
                    $pGoodsData['price'] = $postData['price'];
                    Db::name('shop_promotion_goods')->where('prom_id',$prom_id)->update($pGoodsData);
                    Db::commit();
                }catch(\Exception $e){
                    Db::rollback();
                    $this->error($e->getMessage());
                }
            }else{
                //保存抢购信息
                Db::startTrans();
                try {
                    //保存进抢购表
                    $savePanic = Db::name('shop_promotion_group')->insertGetId($postData);
                    //保存进促销表
                    $promData['p_type'] = 2;
                    $promData['p_id'] = $savePanic;
                    $promData['goods'] = $postData['goods'];
                    $promData['start_time'] = $postData['start_time'];
                    $promData['end_time'] = $postData['end_time'];
                    $saveProm = Db::name('shop_promotion')->insertGetId($promData);
                    $pGoodsData['prom_id'] = $saveProm;
                    $pGoodsData['goods_id'] = $postData['goods'];
                    $pGoodsData['goods_spec'] = $spec_serialize;
                    $pGoodsData['price'] = $postData['price'];
                    Db::name('shop_promotion_goods')->insert($pGoodsData);
                    Db::commit();
                }catch(\Exception $e){
                    Db::rollback();
                    $this->error($e->getMessage());
                }
            }
            $this->success(lang('prom_group_save_success'));
        }
    }



    /**
     * 抢购商品删除，根据管理员权限设置删除方式
     */
    public function del($id = '')
    {
        //删除当前团购活动
        if( $id == '' ) {
            $this->error(lang('PromID_is_null'));
        }
        //获取要删除的总表ID
        $prom_id_arr = Db::name('shop_promotion')->where(['p_type'=>2])->where('p_id in('.$id.')')->column('prom_id');
        $prom_id_arr = implode(',',$prom_id_arr);
        if( is_array($id) ) {
            Db::startTrans();
            try{
                $this->_DB->where('group_id in('.$id.')')->delete();
                Db::name('shop_promotion')->where('prom_id in('.$prom_id_arr.')')->delete();
                Db::name('shop_promotion_goods')->where('prom_id in('.$prom_id_arr.')')->delete();
                Db::commit();
            }catch (\Exception $e){
                Db::rollback();
                $this->error($e->getMessage());
            }

        }else{
            Db::startTrans();
            try{
                $this->_DB->where('group_id',$id)->delete();
                Db::name('shop_promotion')->where('prom_id in("'.$prom_id_arr.'")')->delete();
                Db::name('shop_promotion_goods')->where('prom_id in("'.$prom_id_arr.'")')->delete();
                Db::commit();
            }catch (\Exception $e){
                Db::rollback();
                $this->error($e->getMessage());
            }
        }
        $this->success(lang('delete_success'));
    }
}